Makefile
Adding this Makefile that replicates exactly the gcflags and env variables used by operator-sdk build.
The prow ci job will call `make build`, since calling operator-sdk is not an option.
Also added a `make check` for linting.
=> SREP-905 Added Makefile to be used from ci-operator prow job

README.md, build/Dockerfile
Pushing this Dockerfile to integrate with quay.io pipeline, and to test again ci-operator integration
=> Change Dockerfile to a dual-staged build/run approach

build/Dockerfile.ci-operator
Since ci-operator replaces the FROM clauses on the Dockerfile to what is configured as the base image (a rhel based image), we can't have an alpine as the 2nd FROM, and can't use apk.
While I'm doing research, I'm creating this separate Dockerfile that will be configured for ci-operator, without impacting the working Dockerfile (build/Dockerfile working on quay.io)
=> SREP-1037 Created a separate Dockerfile for ci-operator

build/Dockerfile.ci-operator
The ci-operator workflow forbids setting permissions/UIDs on the Dockerfile, removing it.
=> SREP-1037 Remove permission related clauses from Dockerfile for ci-oper

manifests/03-dedicated-project-admin.ClusterRole.yaml
Was testing some authn/z and found dedicated-admin could not list projects, so couldn't see projects other users in the cluster could create.
=> dedicated-project-admin can list the namespace

Makefile
The target is now quiet and added a test `envtest` to verify it works.  It is called from ci-operator build.  If this fails, we cannot generate the osd-operators registry.
=> isclean make target is quiet unless it fails

Makefile, manifests/10-dedicated-admin-operator.Deployment.yaml, manifests/10-dedicated-admin-operator.Role.yaml, pkg/dedicatedadmin/dedicatedadmin.go
Tried deploying to OSD 3.11 cluster w/o OLM and fixed these:
- Role 'dedicated-admin-operator' now specifies namespace
- Deployment references quay.io/openshift-sre
- Makefile pushes 'latest' tag
- Makefile target 'push' no longer depends on 'build' target
- Added additional blacklist namespaces based on current OSD 3.11 configuration
=> Small fixes and additional namespaces blacklisted.

functions.mk
Rename catalog registry img repo to  add `-registry` at the end
=> SREP-1268 Fix quay.io repo name for catalog img

functions.mk
This PR fixes the yq image to match what Hive is using in their build scripts and updates the select to use the correct name.
=> Update yq image

manifests/35-dedicated-admin-cluster-monitoring-view.ClusterRoleBinding.yaml
In order to get read access to the cluster monitoring stack, the dedicated-admins group gets a ClusterRoleBinding to the ClusterRole cluster-monitoring-view.
=> Enable dedicated-admins to view Cluster Monitoring stack 

README.md
workaround bump commit
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1724742
=> SREP-1686 OLM bug when version hash starts with zero

manifests/04-openshift-logging.Namespace.yaml, manifests/05-dedicated-admins-logging.ClusterRole.yaml, manifests/05-dedicated-admins-logging.RoleBinding.yaml
Allow customer to:
* view, create, edit, delete ClusterLogging CR in openshift-logging NS
* view pods in openshift-logging NS
* view pod logs in openshift-logging NS
This allows customers to opt-in (and then opt-out) to logging by managing the ClusterLogging CR
Note this duplicates creation of the openshift-logging namespace to ensure the namespace exists before rolebinding is created.  It's the same YAML as included in managed-cluster-config repo.
=> Dedicated-admins can manage logging

config/config.go, pkg/controller/namespace/namespace_controller_test.go, pkg/controller/rolebinding/rolebinding_controller_test.go, pkg/dedicatedadmin/dedicatedadmin.go
It was defined in three places inconsistently.  Also had been initially setup with OSD v3 namespaces in mind as well.  Removed the inconsistency, simplified the regex where possible, and dropped the OSD v3 specific patterns.
=> Move blacklist regex to config and clean it up

build/generate-operator-bundle.py, build/templates/olm-artifacts-template.yaml.tmpl, manifests/05-dedicated-admins-logging.Role.yaml, manifests/06-dedicated-admins-logging.RoleBinding.yaml, manifests/35-dedicated-admins-cluster-monitoring-view.RoleBinding.yaml, manifests/36-dedicated-admins-cluster-monitoring-routes.Role.yaml, manifests/37-dedicated-admins-cluster-monitoring-routes.RoleBinding.yaml
- Grant monitoring access only in openshift-monitoring
- Remove all role and rolebindings from CatalogSource image and put in template
Note the work to generate the template file is not in scope of this PR. See https://github.com/openshift/dedicated-admin-operator/issues/57
=> Fixing rbac for logging and monitoring

build/templates/olm-artifacts-template.yaml.tmpl, manifests/80-dedicated-admin-operator-registry.CatalogSource.yaml, manifests/81-dedicated-admin-operator.Subscription.yaml, scripts/templates/template.yaml
Put them into `manifests/` with the params.  This means they can't be applied as-is on a cluster from that directory.
NOTE this only shows up when trying to apply the template with `oc process` which is in another repo.  Can't think of a good way to check this as it's a private repo, not available to the PR check run against github at this time.
=> Added CatalogSource and Subscription back into the template

manifests/02-dedicated-admin-operator.Role.yaml
```
User \"system:serviceaccount:openshift-dedicated-admin:dedicated-admin-operator\" cannot create resource \"configmaps\" in API group \"\" in the namespace \"openshift-dedicated-admin\""
```
Operator needs to create configmaps in it's own namespace. This should be safe to give it all the default verbs because it's scoped to it's own NS.
=> Add additional configmap verbs to operator

build/templates/olm-artifacts-template.yaml.tmpl, manifests/00-dedicated-admins-cluster.ClusterRole.yaml, manifests/07-dedicated-admins-operators.Role.yaml, manifests/07-dedicated-admins-operators.RoleBinding.yaml, manifests/08-dedicated-admins-marketplace.Role.yaml, manifests/08-dedicated-admins-marketplace.RoleBinding.yaml
https://jira.coreos.com/browse/SREP-1370
This assumes the operators displayed are what we want installed.  Those will be managed elsewhere.
A few things to note about this change:
- packagemanifests doesn't have an apiGroup that is reported by the api, so it's just going to be '*'
- we have to grant delete on catalogsourceconfig else deleting operators leaves things in a state where install can't happen, specifically deleting the last operator in an operatorsource
=> Dedicated-admins can install operators from OperatorHub only

build/templates/olm-artifacts-template.yaml.tmpl, manifests/05-dedicated-admins-logging.Role.yaml, manifests/05-dedicated-admins-logging.RoleBinding.yaml
https://jira.coreos.com/browse/SREP-1897
It's one operator we allow installing to a non-default namespace: openshift-logging.
With the recent change to put installation of the operator on the customer's opt-in to logging we need to add allowing installation to the openshift-logging namespace.
=> Update RBAC so customer can install logging operator

build/templates/olm-artifacts-template.yaml.tmpl, manifests/00-dedicated-admins-cluster.ClusterRole.yaml
https://jira.coreos.com/browse/SREP-1945
To make it easier and cleaner to get host from spec of specific routes in core namespaces.
=> Customer can get routes in all namespaces

build/templates/olm-artifacts-template.yaml.tmpl, manifests/04-openshift-logging.Namespace.yaml
https://jira.coreos.com/browse/SREP-1960
It's managed fine in `managed-cluster-config` but it's also created here and it bit us.
=> Exclude openshift-logging namespace from cluster quota

config/config.go
This will allow us to backport the operator to OSD v3,
since v3 has these namespaces blacklisted.
https://jira.coreos.com/browse/SREP-1743
=> Add static namespaces for v3

build/Dockerfile.catalog_registry
The dedicated-admin-operator is missing the --permissive flag from the catalog image builds
https://jira.coreos.com/browse/SREP-2123
=> Add permissive option to image registry initializer

functions.mk
On line 36, we get a value looking something like this `0.1.166-1e758c1` and then immediately check if it exists, if it does, we reset it to `$(OPERATOR_NAME).$$version`, in this case `dedicated-admin-operator.v0.1.166-1e758c1`. Then, we build the new bundle and on line 43 detect what that bundle was.
Line 43 gives us something looking like `0.1.166-1e758c1`. On line 44 we try to check if this is a re-build, and if it is, we should bail out. But, we're comparing `dedicated-admin-operator.v0.1.166-1e758c1 to 0.1.166-1e758c1`.
This change, on line 44, makes sure to compare like to like.
=> :bug: Compare version to correct thing

build/templates/olm-artifacts-template.yaml.tmpl, manifests/00-dedicated-admins-project.ClusterRole.yaml
Since those permissions have been removed from the `admin` ClusterRole in the product between 4.1.18 and 4.1.20 upgrades, I'm adding them to the `dedicated-admin-project` ClusterRole, that gets assigned to each customer NS by the `dedicated-admin-operator`
cc @jmelis @jfchevrette
=> SREP-2178 Added perms for dedicated-admins to manage prometheus objects

build/templates/olm-artifacts-template.yaml.tmpl, manifests/00-dedicated-admins-project.ClusterRole.yaml
In `dedicated-admin-project` Role definition:
`prometheus` -> `prometheuses`
`alertmanager` -> `alertmanagers`
=> SREP-2178 turn resources to plural in Role def

build/templates/olm-artifacts-template.yaml.tmpl, manifests/00-dedicated-admins-cluster.ClusterRole.yaml
Adding `GET, WATCH` Pod, ReplicationController, Service permissions to dedicated-admins, as we have in OSD v3
=> SREP-2178 Permission parity with v3, add GET, WATCH Pod, ReplicationControllers, Services perm to dedicated-admins

config/config.go
The app-create check has been modified to use more than one namespace,
so we need to blacklist all of them.
=> Blacklist namespaces starting with sre-app-check

build/templates/olm-artifacts-template.yaml.tmpl, manifests/00-dedicated-admins-project.ClusterRole.yaml
Give permission to dedicated-admins to manage strimzi kafka operator CRDs.
apiGroup: kafka.strimzi.io
=> SREP-2178 Give permission to dedicated-admins to manage Strimzi Kafka CRDs

build/templates/olm-artifacts-template.yaml.tmpl, manifests/00-dedicated-admins-cluster.ClusterRole.yaml
in order to allow dedicated admins to scrape router metrics, we need some more permissions
=> permissions for OSD-2545

standard.mk
Because we aren't deploying this via app-interface (this is a v3 operator, not v4), we don't need to check the deployed hash.
=> Don't check deployed hash
